In [2]:
#Kütüphaneleri import ediyoruz
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
#csv dosyamızı okuyoruz.
veriler = pd.read_csv("veriler.csv")
print(veriler)

   ulke  boy  kilo  yas cinsiyet
0    tr  130    30   10        e
1    tr  125    36   11        e
2    tr  135    34   10        k
3    tr  133    30    9        k
4    tr  129    38   12        e
5    tr  180    90   30        e
6    tr  190    80   25        e
7    tr  175    90   35        e
8    tr  177    60   22        k
9    us  185   105   33        e
10   us  165    55   27        k
11   us  155    50   44        k
12   us  160    58   39        k
13   us  162    59   41        k
14   us  167    62   55        k
15   fr  174    70   47        e
16   fr  193    90   23        e
17   fr  187    80   27        e
18   fr  183    88   28        e
19   fr  159    40   29        k
20   fr  164    66   32        k
21   fr  166    56   42        k


In [4]:
#verileri encoder yapalım(kategorik verileri nümerik verilere çevirmek)
ulke = veriler.iloc[:,0:1].values #veriler datasetinden ulke sütununu çektik
from sklearn import preprocessing #sklearn kütüphanesinden preprocessing kullanarak verileri LabelEncoder(Nümerik verilere çevirmek) yaptık
le = preprocessing.LabelEncoder()
ulke[:,0]=le.fit_transform(veriler.iloc[:,0]) 
ohe = preprocessing.OneHotEncoder() # kategorik değişkenlerin ikili sistemde tanımlanması sağladık
ulke = ohe.fit_transform(ulke).toarray()
print(ulke)

[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [5]:
c = veriler.iloc[:,-1:].values
from sklearn import preprocessing 
le = preprocessing.LabelEncoder()
c[:,-1] = le.fit_transform(veriler.iloc[:,-1])
ohe = preprocessing.OneHotEncoder()
c = ohe.fit_transform(c).toarray()
print(c)

[[1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]]


In [6]:
sonuc = pd.DataFrame(data=ulke,index=range(22),columns=["fr","tr","us"])
print(sonuc)


     fr   tr   us
0   0.0  1.0  0.0
1   0.0  1.0  0.0
2   0.0  1.0  0.0
3   0.0  1.0  0.0
4   0.0  1.0  0.0
5   0.0  1.0  0.0
6   0.0  1.0  0.0
7   0.0  1.0  0.0
8   0.0  1.0  0.0
9   0.0  0.0  1.0
10  0.0  0.0  1.0
11  0.0  0.0  1.0
12  0.0  0.0  1.0
13  0.0  0.0  1.0
14  0.0  0.0  1.0
15  1.0  0.0  0.0
16  1.0  0.0  0.0
17  1.0  0.0  0.0
18  1.0  0.0  0.0
19  1.0  0.0  0.0
20  1.0  0.0  0.0
21  1.0  0.0  0.0


In [7]:
Yas = veriler.iloc[:,1:4].values
sonuc2 = pd.DataFrame(data=Yas,index=range(22),columns=["boy","kilo","yas"])
print(sonuc2)

    boy  kilo  yas
0   130    30   10
1   125    36   11
2   135    34   10
3   133    30    9
4   129    38   12
5   180    90   30
6   190    80   25
7   175    90   35
8   177    60   22
9   185   105   33
10  165    55   27
11  155    50   44
12  160    58   39
13  162    59   41
14  167    62   55
15  174    70   47
16  193    90   23
17  187    80   27
18  183    88   28
19  159    40   29
20  164    66   32
21  166    56   42


In [8]:
cinsiyet = veriler.iloc[:,-1].values
sonuc3=pd.DataFrame(data=c[:,:1],index=range(22),columns=["cinsiyet"])
print(sonuc3)

    cinsiyet
0        1.0
1        1.0
2        0.0
3        0.0
4        1.0
5        1.0
6        1.0
7        1.0
8        0.0
9        1.0
10       0.0
11       0.0
12       0.0
13       0.0
14       0.0
15       1.0
16       1.0
17       1.0
18       1.0
19       0.0
20       0.0
21       0.0


In [9]:
s = pd.concat([sonuc,sonuc2],axis=1) #dataframeleri birleştirdik
print(s)

     fr   tr   us  boy  kilo  yas
0   0.0  1.0  0.0  130    30   10
1   0.0  1.0  0.0  125    36   11
2   0.0  1.0  0.0  135    34   10
3   0.0  1.0  0.0  133    30    9
4   0.0  1.0  0.0  129    38   12
5   0.0  1.0  0.0  180    90   30
6   0.0  1.0  0.0  190    80   25
7   0.0  1.0  0.0  175    90   35
8   0.0  1.0  0.0  177    60   22
9   0.0  0.0  1.0  185   105   33
10  0.0  0.0  1.0  165    55   27
11  0.0  0.0  1.0  155    50   44
12  0.0  0.0  1.0  160    58   39
13  0.0  0.0  1.0  162    59   41
14  0.0  0.0  1.0  167    62   55
15  1.0  0.0  0.0  174    70   47
16  1.0  0.0  0.0  193    90   23
17  1.0  0.0  0.0  187    80   27
18  1.0  0.0  0.0  183    88   28
19  1.0  0.0  0.0  159    40   29
20  1.0  0.0  0.0  164    66   32
21  1.0  0.0  0.0  166    56   42


In [10]:
s2=pd.concat([s,sonuc3],axis=1) # tüm verilerimiz nümerik hale geldi
print(s2)

     fr   tr   us  boy  kilo  yas  cinsiyet
0   0.0  1.0  0.0  130    30   10       1.0
1   0.0  1.0  0.0  125    36   11       1.0
2   0.0  1.0  0.0  135    34   10       0.0
3   0.0  1.0  0.0  133    30    9       0.0
4   0.0  1.0  0.0  129    38   12       1.0
5   0.0  1.0  0.0  180    90   30       1.0
6   0.0  1.0  0.0  190    80   25       1.0
7   0.0  1.0  0.0  175    90   35       1.0
8   0.0  1.0  0.0  177    60   22       0.0
9   0.0  0.0  1.0  185   105   33       1.0
10  0.0  0.0  1.0  165    55   27       0.0
11  0.0  0.0  1.0  155    50   44       0.0
12  0.0  0.0  1.0  160    58   39       0.0
13  0.0  0.0  1.0  162    59   41       0.0
14  0.0  0.0  1.0  167    62   55       0.0
15  1.0  0.0  0.0  174    70   47       1.0
16  1.0  0.0  0.0  193    90   23       1.0
17  1.0  0.0  0.0  187    80   27       1.0
18  1.0  0.0  0.0  183    88   28       1.0
19  1.0  0.0  0.0  159    40   29       0.0
20  1.0  0.0  0.0  164    66   32       0.0
21  1.0  0.0  0.0  166    56   4

In [11]:
from sklearn.model_selection import train_test_split
x_train , x_test ,y_train,y_test =train_test_split(s,sonuc3,test_size=0.33,random_state=0)
print(x_train)

     fr   tr   us  boy  kilo  yas
8   0.0  1.0  0.0  177    60   22
6   0.0  1.0  0.0  190    80   25
16  1.0  0.0  0.0  193    90   23
4   0.0  1.0  0.0  129    38   12
2   0.0  1.0  0.0  135    34   10
5   0.0  1.0  0.0  180    90   30
17  1.0  0.0  0.0  187    80   27
9   0.0  0.0  1.0  185   105   33
7   0.0  1.0  0.0  175    90   35
18  1.0  0.0  0.0  183    88   28
3   0.0  1.0  0.0  133    30    9
0   0.0  1.0  0.0  130    30   10
15  1.0  0.0  0.0  174    70   47
12  0.0  0.0  1.0  160    58   39


In [12]:
from sklearn.model_selection import train_test_split
x_train , x_test ,y_train,y_test =train_test_split(s,sonuc3,test_size=0.33,random_state=0)
print(x_test)

     fr   tr   us  boy  kilo  yas
20  1.0  0.0  0.0  164    66   32
10  0.0  0.0  1.0  165    55   27
14  0.0  0.0  1.0  167    62   55
13  0.0  0.0  1.0  162    59   41
1   0.0  1.0  0.0  125    36   11
21  1.0  0.0  0.0  166    56   42
11  0.0  0.0  1.0  155    50   44
19  1.0  0.0  0.0  159    40   29


In [13]:
from sklearn.model_selection import train_test_split
x_train , x_test ,y_train,y_test =train_test_split(s,sonuc3,test_size=0.33,random_state=0)
print(y_train)

    cinsiyet
8        0.0
6        1.0
16       1.0
4        1.0
2        0.0
5        1.0
17       1.0
9        1.0
7        1.0
18       1.0
3        0.0
0        1.0
15       1.0
12       0.0


In [14]:
from sklearn.model_selection import train_test_split
x_train , x_test ,y_train,y_test =train_test_split(s,sonuc3,test_size=0.33,random_state=0)
print(y_test)

    cinsiyet
20       0.0
10       0.0
14       0.0
13       0.0
1        1.0
21       0.0
11       0.0
19       0.0


In [15]:
#öznitelik ölçeklemek
#standart scaler : farklı birimlere karşılık gelen değerleri aynı tipe çevirmek
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(x_train)
X_test = sc.fit_transform(x_test)
print(X_train)

[[-0.63245553  0.8660254  -0.40824829  0.45049444 -0.29657884 -0.26680787]
 [-0.63245553  0.8660254  -0.40824829  1.00824945  0.5096549   0.        ]
 [ 1.58113883 -1.15470054 -0.40824829  1.13696215  0.91277178 -0.17787191]
 [-0.63245553  0.8660254  -0.40824829 -1.6089087  -1.18343596 -1.15616745]
 [-0.63245553  0.8660254  -0.40824829 -1.35148331 -1.34468271 -1.33403936]
 [-0.63245553  0.8660254  -0.40824829  0.57920713  0.91277178  0.44467979]
 [ 1.58113883 -1.15470054 -0.40824829  0.87953676  0.5096549   0.17787191]
 [-0.63245553 -1.15470054  2.44948974  0.79372829  1.51744708  0.71148766]
 [-0.63245553  0.8660254  -0.40824829  0.36468597  0.91277178  0.88935957]
 [ 1.58113883 -1.15470054 -0.40824829  0.70791983  0.8321484   0.26680787]
 [-0.63245553  0.8660254  -0.40824829 -1.43729177 -1.50592946 -1.42297532]
 [-0.63245553  0.8660254  -0.40824829 -1.56600447 -1.50592946 -1.33403936]
 [ 1.58113883 -1.15470054 -0.40824829  0.32178174  0.10653803  1.95659106]
 [-0.63245553 -1.15470054

In [16]:
#öznitelik ölçeklemek
#standart scaler : farklı birimlere karşılık gelen değerleri aynı tipe çevirmek
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(x_train)
X_test = sc.fit_transform(x_test)
print(X_test)

[[ 1.29099445 -0.37796447 -1.          0.47240026  1.32853794 -0.24991255]
 [-0.77459667 -0.37796447  1.          0.54952683  0.20439045 -0.64977262]
 [-0.77459667 -0.37796447  1.          0.70377998  0.91975703  1.58944379]
 [-0.77459667 -0.37796447  1.          0.31814711  0.61317136  0.46983559]
 [-0.77459667  2.64575131 -1.         -2.53553608 -1.73731884 -1.92932485]
 [ 1.29099445 -0.37796447 -1.          0.6266534   0.30658568  0.5498076 ]
 [-0.77459667 -0.37796447  1.         -0.2217389  -0.30658568  0.70975163]
 [ 1.29099445 -0.37796447 -1.          0.08676739 -1.32853794 -0.48982859]]


In [17]:
from sklearn.model_selection import train_test_split
x_train , x_test ,y_train,y_test =train_test_split(s,sonuc3,test_size=0.33,random_state=0)
from sklearn.linear_model import LinearRegression #çoklu doğrusal regrasyon 
regressor = LinearRegression() # Regressor adında bir sınıf tanımladık
regressor.fit(x_train,y_train) #fit fonksiyonu yardımıyla x_train ile y_train arasında doğrusal model oluşturuyor
y_pred = regressor.predict(x_test) #x_test kısmını tahmin edip y_prede ata 
print(y_pred)

[[ 0.98720204]
 [-0.12036863]
 [ 0.05009703]
 [ 0.07137418]
 [ 0.72473935]
 [ 0.64615044]
 [-0.03567453]
 [ 0.32612171]]


In [18]:
boy = s2.iloc[:,3:4].values
sol = s2.iloc[:,:3]
sag = s2.iloc[:,4:]
veri = pd.concat([sol,sag],axis=1)
print(veri)

     fr   tr   us  kilo  yas  cinsiyet
0   0.0  1.0  0.0    30   10       1.0
1   0.0  1.0  0.0    36   11       1.0
2   0.0  1.0  0.0    34   10       0.0
3   0.0  1.0  0.0    30    9       0.0
4   0.0  1.0  0.0    38   12       1.0
5   0.0  1.0  0.0    90   30       1.0
6   0.0  1.0  0.0    80   25       1.0
7   0.0  1.0  0.0    90   35       1.0
8   0.0  1.0  0.0    60   22       0.0
9   0.0  0.0  1.0   105   33       1.0
10  0.0  0.0  1.0    55   27       0.0
11  0.0  0.0  1.0    50   44       0.0
12  0.0  0.0  1.0    58   39       0.0
13  0.0  0.0  1.0    59   41       0.0
14  0.0  0.0  1.0    62   55       0.0
15  1.0  0.0  0.0    70   47       1.0
16  1.0  0.0  0.0    90   23       1.0
17  1.0  0.0  0.0    80   27       1.0
18  1.0  0.0  0.0    88   28       1.0
19  1.0  0.0  0.0    40   29       0.0
20  1.0  0.0  0.0    66   32       0.0
21  1.0  0.0  0.0    56   42       0.0


In [19]:
from sklearn.model_selection import train_test_split
x_train , x_test ,y_train,y_test =train_test_split(veri,boy,test_size=0.33,random_state=0)
print(y_test)

[[164]
 [165]
 [167]
 [162]
 [125]
 [166]
 [155]
 [159]]


In [20]:
from sklearn.model_selection import train_test_split
x_train , x_test ,y_train,y_test =train_test_split(veri,boy,test_size=0.33,random_state=0)
print(y_train)

[[177]
 [190]
 [193]
 [129]
 [135]
 [180]
 [187]
 [185]
 [175]
 [183]
 [133]
 [130]
 [174]
 [160]]


In [21]:
from sklearn.model_selection import train_test_split
x_train , x_test ,y_train,y_test =train_test_split(veri,boy,test_size=0.33,random_state=0)
print(x_train)

     fr   tr   us  kilo  yas  cinsiyet
8   0.0  1.0  0.0    60   22       0.0
6   0.0  1.0  0.0    80   25       1.0
16  1.0  0.0  0.0    90   23       1.0
4   0.0  1.0  0.0    38   12       1.0
2   0.0  1.0  0.0    34   10       0.0
5   0.0  1.0  0.0    90   30       1.0
17  1.0  0.0  0.0    80   27       1.0
9   0.0  0.0  1.0   105   33       1.0
7   0.0  1.0  0.0    90   35       1.0
18  1.0  0.0  0.0    88   28       1.0
3   0.0  1.0  0.0    30    9       0.0
0   0.0  1.0  0.0    30   10       1.0
15  1.0  0.0  0.0    70   47       1.0
12  0.0  0.0  1.0    58   39       0.0


In [22]:
from sklearn.model_selection import train_test_split
x_train , x_test ,y_train,y_test =train_test_split(veri,boy,test_size=0.33,random_state=0)
print(x_test)

     fr   tr   us  kilo  yas  cinsiyet
20  1.0  0.0  0.0    66   32       0.0
10  0.0  0.0  1.0    55   27       0.0
14  0.0  0.0  1.0    62   55       0.0
13  0.0  0.0  1.0    59   41       0.0
1   0.0  1.0  0.0    36   11       1.0
21  1.0  0.0  0.0    56   42       0.0
11  0.0  0.0  1.0    50   44       0.0
19  1.0  0.0  0.0    40   29       0.0


In [23]:
from sklearn.linear_model import LinearRegression #çoklu doğrusal regrasyon 
regressor2 = LinearRegression() # Regressor adında bir sınıf tanımladık
regressor2.fit(x_train,y_train) #fit fonksiyonu yardımıyla x_train ile y_train arasında doğrusal model oluşturuyor
y_pred = regressor2.predict(x_test) #x_test kısmını tahmin edip y_pred yap 
print(y_pred)

[[182.26638686]
 [152.87161474]
 [162.79386375]
 [158.30668577]
 [130.82888952]
 [173.96138408]
 [150.12782663]
 [157.26898922]]


İstatistikte, p değeri, bir istatistiksel modele bağlı olarak gözlemlenen örneklem sonuçlarının (bir test istatistiği) ne kadar aşırı olduğunu ölçmek için kullanılan bir fonksiyondur. 
Backward elimination : tüm istatistiksel değerleri hesapladıktan sonra en yüksek P değerine sahip olan değeri sil tüm P değerleri 0'a yaklaşana kadar devam et


In [24]:
import statsmodels.api as sm
X = np.append(arr = np.ones((22,1)).astype(int), values= veri, axis=1)
X_l = veri.iloc[:,[0,1,2,3,4,5,]].values
model = sm.OLS(boy,X_l).fit()
print(model.summary())


                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.885
Model:                            OLS   Adj. R-squared:                  0.849
Method:                 Least Squares   F-statistic:                     24.69
Date:                Sun, 28 Nov 2021   Prob (F-statistic):           5.41e-07
Time:                        12:52:49   Log-Likelihood:                -73.950
No. Observations:                  22   AIC:                             159.9
Df Residuals:                      16   BIC:                             166.4
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1           114.0688      8.145     14.005      0.0

In [25]:
import statsmodels.api as sm
X = np.append(arr = np.ones((22,1)).astype(int), values= veri, axis=1)
X_l = veri.iloc[:,[0,1,2,3,5,]].values
model = sm.OLS(boy,X_l).fit()
print(model.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.884
Model:                            OLS   Adj. R-squared:                  0.857
Method:                 Least Squares   F-statistic:                     32.47
Date:                Sun, 28 Nov 2021   Prob (F-statistic):           9.32e-08
Time:                        12:52:49   Log-Likelihood:                -74.043
No. Observations:                  22   AIC:                             158.1
Df Residuals:                      17   BIC:                             163.5
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1           115.6583      6.734     17.175      0.0

In [27]:
from sklearn.linear_model import LinearRegression #çoklu doğrusal regrasyon 
regressor2 = LinearRegression() # Regressor adında bir sınıf tanımladık
regressor2.fit(x_train,y_train) #fit fonksiyonu yardımıyla x_train ile y_train arasında doğrusal model oluşturuyor
y_pred = regressor2.predict(x_test) #x_test kısmını tahmin edip y_pred yap 
print(y_pred)

[[182.26638686]
 [152.87161474]
 [162.79386375]
 [158.30668577]
 [130.82888952]
 [173.96138408]
 [150.12782663]
 [157.26898922]]


forward eliminationda ise en küçük P değerlerini silerek ilerle

In [28]:
import statsmodels.api as sm
X = np.append(arr = np.ones((22,1)).astype(int), values= veri, axis=1)
X_l = veri.iloc[:,[0,1,2,3,4,5,]].values
model = sm.OLS(boy,X_l).fit()
print(model.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.885
Model:                            OLS   Adj. R-squared:                  0.849
Method:                 Least Squares   F-statistic:                     24.69
Date:                Sun, 28 Nov 2021   Prob (F-statistic):           5.41e-07
Time:                        12:54:12   Log-Likelihood:                -73.950
No. Observations:                  22   AIC:                             159.9
Df Residuals:                      16   BIC:                             166.4
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1           114.0688      8.145     14.005      0.0

In [29]:
import statsmodels.api as sm
X = np.append(arr = np.ones((22,1)).astype(int), values= veri, axis=1)
X_l = veri.iloc[:,[0,1,2,3,4,]].values
model = sm.OLS(boy,X_l).fit()
print(model.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.854
Model:                            OLS   Adj. R-squared:                  0.819
Method:                 Least Squares   F-statistic:                     24.80
Date:                Sun, 28 Nov 2021   Prob (F-statistic):           6.63e-07
Time:                        12:54:36   Log-Likelihood:                -76.623
No. Observations:                  22   AIC:                             163.2
Df Residuals:                      17   BIC:                             168.7
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1           115.2550      8.901     12.949      0.0

In [30]:
import statsmodels.api as sm
X = np.append(arr = np.ones((22,1)).astype(int), values= veri, axis=1)
X_l = veri.iloc[:,[0,1,2,3,]].values
model = sm.OLS(boy,X_l).fit()
print(model.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.847
Model:                            OLS   Adj. R-squared:                  0.821
Method:                 Least Squares   F-statistic:                     33.16
Date:                Sun, 28 Nov 2021   Prob (F-statistic):           1.52e-07
Time:                        12:55:03   Log-Likelihood:                -77.131
No. Observations:                  22   AIC:                             162.3
Df Residuals:                      18   BIC:                             166.6
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1           119.8136      7.265     16.491      0.0